### ISSUE TITLE
Allow configuration of the gateway name.

### ISSUE THREAD

**Issue by SaberUK** [kiwiirc/webircgateway#14]
InspIRCd 3.0 allows filtering of WebIRC gateways into connect classes by the gateway name sent in `WEBIRC`. Currently webircgateway hardcodes this value as `websocketgateway`. It would be useful if users of webircgateway could configure this value to allow server operators to filter connections into appropriate connect classes.

**Comment by prawnsalad** [comment]
Good idea, will get this in.

**Comment by prawnsalad** [comment]
Forgot to close this. https://github.com/kiwiirc/webircgateway/commit/22a8930d479df0d0f4a0544e2616bed3c641da08
