### ISSUE TITLE
IP database integration. Is it possible via plugin?

### ISSUE THREAD

**Issue by obsh** [kiwiirc/webircgateway#64]
Hi, I want to integrate Maxmind's GeoLite2 IP database and:
- detect client country
- introduce new placeholder for country value in realname field.

Could you clarify if such extension is possible via plugins functionality, please?

**Comment by prawnsalad** [comment]
Yes this is possible. Untested, but something like:
~~~golang
package main

import (
	"github.com/kiwiirc/webircgateway/pkg/proxy"
	"github.com/kiwiirc/webircgateway/pkg/webircgateway"
)


func Start(gateway *webircgateway.Gateway, pluginsQuit *sync.WaitGroup) {
	gateway.Log(2, "Example lugin loading")

	webircgateway.HookRegister("irc.connection.pre", hookIrcConnectionPre)
	pluginsQuit.Done()
}


func hookIrcConnectionPre(hook *webircgateway.HookIrcConnectionPre) {
    // Lookup geo info here
    // hook.Client == https://github.com/kiwiirc/webircgateway/blob/master/pkg/webircgateway/client.go#L41
    // hook.Client.IrcState == https://github.com/kiwiirc/webircgateway/blob/master/pkg/irc/state.go#L9
}
~~~

Add into a file at `plugins/geoip/plugin.go` and run `make` to build it all

**Comment by obsh** [comment]
Hi @prawnsalad, thank you for recommendation! I'm working on implementation it's going fine overall.

Could you also suggest the best way to tear down plugin resources? I'm opening geoIP database in the `Start` method,  and using it in `hookIrcConnectionPre`. Is there some hook when server is shutting down so that I can close the database?

**Comment by prawnsalad** [comment]
I've just added the all important hook that you can tap into when the gateway is closing down, just before any built in server are shutdown.

Your existing `pluginsQuit.Done()` should be moved to whenever your plugin is ready to be stopped.

In your plugin:
~~~golang
webircgateway.HookRegister("gateway.closing", func(hook *webircgateway.HookGatewayClosing) {
	go func() {
		fmt.Println("gateway is closing. Waiting 5sec")
		time.Sleep(time.Second * 5)
		pluginsQuit.Done()
	}()
})
~~~
